#pragma once

#include "CoreMinimal.h"
#include "EdGraph/EdGraphPin.h"

#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

namespace NeoLuaPin
{
	// Get a usable pin name for Lua consumers.
	// Priority: display name (if substantive) > PinName (if substantive) > directional index fallback.
	// Material/SoundCue set PinFriendlyName to " " (space) for unnamed pins, so we skip whitespace-only names.
	inline FString GetUsablePinName(UEdGraphPin* Pin)
	{
		// 1. Try display name (friendly name shown in editor)
		FString DisplayName = Pin->GetDisplayName().ToString();
		if (!DisplayName.TrimStartAndEnd().IsEmpty())
		{
			return DisplayName;
		}

		// 2. Try PinName (internal name, e.g. "Output_0", "Input2", "RGB")
		FString PinName = Pin->PinName.ToString();
		if (!PinName.TrimStartAndEnd().IsEmpty())
		{
			return PinName;
		}

		// 3. Generate a directional index fallback (in_0, out_0, etc.)
		UEdGraphNode* Node = Pin->GetOwningNodeUnchecked();
		int32 Idx = 0;
		if (Node)
		{
			for (UEdGraphPin* P : Node->Pins)
			{
				if (P == Pin) break;
				if (P && P->Direction == Pin->Direction) Idx++;
			}
		}
		return (Pin->Direction == EGPD_Input)
			? FString::Printf(TEXT("in_%d"), Idx)
			: FString::Printf(TEXT("out_%d"), Idx);
	}

	inline sol::table BuildPinTable(sol::state_view& LuaView, UEdGraphPin* Pin)
	{
		FString PinName = GetUsablePinName(Pin);

		sol::table PinInfo = LuaView.create_table();
		PinInfo["name"] = TCHAR_TO_UTF8(*PinName);
		// Also expose the raw internal name for debugging
		PinInfo["raw_name"] = TCHAR_TO_UTF8(*Pin->PinName.ToString());
		PinInfo["type"] = TCHAR_TO_UTF8(*Pin->PinType.PinCategory.ToString());
		if (Pin->PinType.PinSubCategoryObject.IsValid())
		{
			PinInfo["sub_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinSubCategoryObject->GetName());
		}
		else if (!Pin->PinType.PinSubCategory.IsNone())
		{
			PinInfo["sub_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinSubCategory.ToString());
		}
		if (Pin->PinType.ContainerType == EPinContainerType::Array)
			PinInfo["container"] = "array";
		else if (Pin->PinType.ContainerType == EPinContainerType::Set)
			PinInfo["container"] = "set";
		else if (Pin->PinType.ContainerType == EPinContainerType::Map)
			PinInfo["container"] = "map";
		// Use GetDefaultAsString() to unify string values and object references
		// (class/object pins store value in DefaultObject, not DefaultValue)
		FString DefaultStr = Pin->GetDefaultAsString();
		if (!DefaultStr.IsEmpty())
		{
			PinInfo["default"] = TCHAR_TO_UTF8(*DefaultStr);
		}
		PinInfo["connected"] = Pin->LinkedTo.Num() > 0;
		if (Pin->DefaultObject)
		{
			// Keep for backward compat — agents may check this field
			PinInfo["default_object"] = TCHAR_TO_UTF8(*Pin->DefaultObject->GetPathName());
		}
		if (!Pin->DefaultTextValue.IsEmpty())
		{
			PinInfo["default_text"] = TCHAR_TO_UTF8(*Pin->DefaultTextValue.ToString());
		}
		if (!Pin->AutogeneratedDefaultValue.IsEmpty())
		{
			PinInfo["autogenerated_default"] = TCHAR_TO_UTF8(*Pin->AutogeneratedDefaultValue);
		}
		PinInfo["is_hidden"] = static_cast<bool>(Pin->bHidden);
		PinInfo["is_orphaned"] = static_cast<bool>(Pin->bOrphanedPin);
		if (Pin->bAdvancedView) PinInfo["is_advanced"] = true;
		PinInfo["direction"] = (Pin->Direction == EGPD_Input) ? "input" : "output";
		PinInfo["linked_to_count"] = Pin->LinkedTo.Num();
		if (Pin->LinkedTo.Num() > 0)
		{
			sol::table LinkedToTable = LuaView.create_table();
			int32 LtIdx = 1;
			for (UEdGraphPin* LinkedPin : Pin->LinkedTo)
			{
				if (!LinkedPin) continue;
				UEdGraphNode* LinkedNode = LinkedPin->GetOwningNodeUnchecked();
				if (!LinkedNode) continue;
				sol::table LtEntry = LuaView.create_table();
				LtEntry["node_id"] = TCHAR_TO_UTF8(*LinkedNode->NodeGuid.ToString());
				LtEntry["node_title"] = TCHAR_TO_UTF8(*LinkedNode->GetNodeTitle(ENodeTitleType::ListView).ToString());
				LtEntry["pin_name"] = TCHAR_TO_UTF8(*GetUsablePinName(LinkedPin));
				LinkedToTable[LtIdx++] = LtEntry;
			}
			PinInfo["linked_to"] = LinkedToTable;
		}
		if (Pin->PinType.bIsReference) PinInfo["is_reference"] = true;
		if (Pin->PinType.bIsConst) PinInfo["is_const"] = true;
		if (Pin->PinType.bIsWeakPointer) PinInfo["is_weak_pointer"] = true;
		if (Pin->PinType.ContainerType == EPinContainerType::Map && Pin->PinType.PinValueType.TerminalCategory != NAME_None)
		{
			PinInfo["value_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinValueType.TerminalCategory.ToString());
			if (Pin->PinType.PinValueType.TerminalSubCategoryObject.IsValid())
				PinInfo["value_sub_type"] = TCHAR_TO_UTF8(*Pin->PinType.PinValueType.TerminalSubCategoryObject->GetName());
		}
		// Expose split sub-pins (e.g. Vector → X/Y/Z) so agents see the full picture
		if (Pin->SubPins.Num() > 0)
		{
			sol::table SubPinsTable = LuaView.create_table();
			int32 SubIdx = 1;
			for (UEdGraphPin* SubPin : Pin->SubPins)
			{
				if (!SubPin) continue;
				SubPinsTable[SubIdx++] = BuildPinTable(LuaView, SubPin);
			}
			PinInfo["sub_pins"] = SubPinsTable;
		}
		return PinInfo;
	}
}
